### ISSUE TITLE
socket.error when calling create_all()

### ISSUE THREAD

**Issue by asib** [e-dard/flask-s3#39]
I was trying to setup flask-s3 for my app but I kept getting a `socket.error` (either `broken pipe` or `connection reset by peer`) when running `flask_s3.create_all(app)` in a python shell as suggested in the docs. I had already made the bucket and was just trying to upload my static assets.

The fix appears to be to set the (undocumented) config variable `S3_REGION` to the region in which you created your bucket. However, this caused an error for me when the `create_all()` function tried to call `conn.create_bucket(bucket_name)`. By changing this call to a `get_bucket()` call, I was able to execute `create_all()` without error.

**Comment by SunDwarf** [comment]
Hi, could you by any chance give a full log and your code changes?

**Comment by asib** [comment]
Hi, sorry for taking so long.

I've just tried to setup a simple app to illustrate this, but I've come up against a different problem. When I try to run `create_all()` I get `TypeError: decoding Unicode is not supported` with the following stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jacobfenton/Desktop/Python/create_all_test/venv/lib/python2.7/site-packages/flask_s3.py", line 290, in create_all
    _upload_files(s3, app, all_files, bucket_name)
  File "/Users/jacobfenton/Desktop/Python/create_all_test/venv/lib/python2.7/site-packages/flask_s3.py", line 187, in _upload_files
    bucket, hashes=hashes))
  File "/Users/jacobfenton/Desktop/Python/create_all_test/venv/lib/python2.7/site-packages/flask_s3.py", line 144, in _write_files
    asset_loc)
  File "/Users/jacobfenton/Desktop/Python/create_all_test/venv/lib/python2.7/site-packages/flask_s3.py", line 133, in _static_folder_path
    return six.u('%s/%s' % (static_url.rstrip('/'), rel_asset.lstrip('/')))
  File "/Users/jacobfenton/Desktop/Python/create_all_test/venv/lib/python2.7/site-packages/six.py", line 621, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported
```

**Comment by SunDwarf** [comment]
I believe that is fixed in commit d8ab184531b650a416066987d552f67902ff7382 - I don't have a Py2 instance available currently, can you test it? Before I push to pypi.

**Comment by asib** [comment]
No still getting the same error

**Comment by SunDwarf** [comment]
Oh for fucks sake python 2, let me fix this then

**Comment by asib** [comment]
Just tried again with the latest commit and got no errors, so it would appear the unicode problem has been solved as well as whatever my original problem was.
