### ISSUE TITLE
ImportError: No module named boto3

### ISSUE THREAD

**Issue by vincent-kuwornu** [e-dard/flask-s3#54]
$ pip install flask-s3
Collecting flask-s3
  Downloading Flask-S3-0.2.7.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/2m/8277clyj4bxft9phn9znvhn8_j08wx/T/pip-build-_D5bzk/flask-s3/setup.py", line 8, in <module>
        from flask_s3 import __version__
      File "flask_s3.py", line 18, in <module>
        import boto3
    ImportError: No module named boto3

**Comment by SunDwarf** [comment]
sec

**Comment by SunDwarf** [comment]
fixed, redownload
