### ISSUE TITLE
GZipping Fails

### ISSUE THREAD

**Issue by gtalarico** [e-dard/flask-s3#81]
Python 3.5.2
Only fails when GZIP is enabled.
Trace stack:

Maybe related?
http://stackoverflow.com/questions/32075135/python-3-in-memory-zipfile-error-string-argument-expected-got-bytes

```
[DEBUG] Uploading C:\Users\gtalarico\Dropbox\Shared\dev-ubuntu\repos\revitapidocs\app\static\favicon.ico to revitapidocs as static/favicon.ico [flask_s3.py](246)[07:17:07]
Traceback (most recent call last):
  File "upload-s3-assets.py", line 9, in <module>
    flask_s3.create_all(app)
  File "C:\Users\gtalarico\Dropbox\Shared\dev-ubuntu\.virtualenvs-win8\revitapidocs\lib\site-packages\flask_s3.py", line 453, in create_all
    _upload_files(s3, app, all_files, bucket_name)
  File "C:\Users\gtalarico\Dropbox\Shared\dev-ubuntu\.virtualenvs-win8\revitapidocs\lib\site-packages\flask_s3.py", line 319, in _upload_files
    names, bucket, hashes=hashes))
  File "C:\Users\gtalarico\Dropbox\Shared\dev-ubuntu\.virtualenvs-win8\revitapidocs\lib\site-packages\flask_s3.py", line 295, in _write_files
    compressed)
  File "c:\python\Lib\gzip.py", line 192, in __init__
    self._write_gzip_header()
  File "c:\python\Lib\gzip.py", line 220, in _write_gzip_header
    self.fileobj.write(b'\037\213')             # magic header
TypeError: string argument expected, got 'bytes'
```

**Comment by gtalarico** [comment]
Using six.BytesIO fixes it.

http://stackoverflow.com/questions/32075135/python-3-in-memory-zipfile-error-string-argument-expected-got-bytes
